# Generated by Django 4.1.4 on 2023-01-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('Taklif', 'Taklif'), ('Shikoyat', 'Shikoyat')], default='Taklif', max_length=8)),
                ('message', models.TextField(max_length=700)),
                ('is_view', models.BooleanField(default=False)),
            ],
        ),
    ]
