# Generated by Django 4.1.4 on 2023-01-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amCharts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_organiser', models.BooleanField(default=False)),
                ('is_agent', models.BooleanField(default=False)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('following', models.ManyToManyField(blank=True, related_name='followers', to='amCharts.myuser')),
            ],
        ),
    ]
