# Generated by Django 4.1.4 on 2023-01-28 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amCharts', '0002_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='following',
        ),
    ]
