# Generated by Django 4.1.4 on 2023-01-29 16:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('amCharts', '0003_remove_myuser_following'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('caption', models.TextField(max_length=700)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('chart_type', models.CharField(choices=[('Pie', 'Pie Chart'), ('Column', 'Column Chart')], default='Pie', max_length=15)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart', to='amCharts.myuser')),
            ],
        ),
    ]
