# Generated by Django 4.1.4 on 2023-01-30 15:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('amCharts', '0004_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='amCharts.myuser'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile/profile.jpg', upload_to='profile')),
                ('bio', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('is_verify', models.BooleanField(default=False)),
                ('custom_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='amCharts.myuser')),
            ],
            options={
                'verbose_name': 'My Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('value', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element', to='amCharts.chart')),
            ],
        ),
        migrations.CreateModel(
            name='accountVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('verfy_account1', models.URLField(unique=True)),
                ('message', models.TextField(max_length=700)),
                ('request_username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='req_user', to='amCharts.myuser')),
            ],
        ),
    ]
